services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "nc", "-z", "0.0.0.0", "2181" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093 # (-)
      # внутренние клиенты также используют 9092 для подключения к kafka, 9093 для внешних соединений
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093 #(-)
      # слушаем на порту 9092 для внутренних docker соединений, на порту 9093 для внешних соединений

      #порты у (-) должны совпадать если ports: x:x - одинаковые значения
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      # KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      # если было бы так то тогда проброс портов должен был быть ports 9093:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sorokindb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./db_data_fs:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
  gateway:
    hostname: gateway
    container_name: gateway
    build: ./gateway
    ports:
      - "8080:8080"

  auth:
    hostname: auth
    container_name: auth
    build: ./auth
    ports:
      - "8081:8080"
  event-manager:
    hostname: event-manager
    container_name: event-manager
    build: ./event-manager
    ports:
      - "8082:8080"

  event-notificator:
    hostname: event-notificator
    container_name: event-notificator
    build: ./event-notificator
    ports:
      - "8083:8080"
