server:
  port: 8080
spring:
  application:
    name: gateway
  kafka:
    bootstrap-servers: kafka:9092
jwt:
  secret: "verySecretKey12345goihoigjiohfhdklnffuiehniunfejoifjelkfjeifdjojfeiodjlkfcmdflkgfjgoierjfgioioegioijeogjoiojgo"

