spring:
  application:
    name: auth
  datasource:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      platform: postgres


    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: false
      properties:
        hibernate:
          format_sql: true
  kafka:
    bootstrap-servers: kafka:9092

success:
  register:
    message: "We were successfully registered"
  booking:
    message: "You were successfully registered. We'll wait you."
jwt:
  expiration: 3600000
swagger:
  enabled: true
  path: /swagger-ui.html
  base-package: com.ddos.auth.controller
  title: Auth Service API
  description: API documentation for Auth Service
  version: 1.0.0