server:
  port: 8080

spring:
  application:
    name: event-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # ?? ????? Flyway, ??????? schema ???????? ?? ?????
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jwt:
    secret: "verySecretKey12345goihoigjiohfhdklnffuiehniunfejoifjelkfjeifdjojfeiodjlkfcmdflkgfjgoierjfgioioegioijeogjoiojgo"
    expiration: 3600000
success:
  register:
    message: "We were successfully registered"
